# This software is a part of ISAR.
# Copyright (C) 2026 Siemens

require conf/machine/rpi5-arm64-v8-efi.inc

IMAGER_INSTALL:wic += "${SYSTEMD_BOOTLOADER_INSTALL}"

# NOTE: we need Linux >= 6.18
KERNEL_IMAGE_PKG ?= "linux-image-arm64"
IMAGE_PREINSTALL += "initramfs-tools"

DISTRO_APT_SOURCES:append = " conf/distro/debian-trixie-backports.list"
DISTRO_APT_PREFERENCES:append = " conf/distro/rpi5-preferences.conf"
